### PR TITLE
Build RevRegDelta request from RevRegEntry path with appropriate quer…

### LINKED ISSUE #13: REV REG ENTRY / DELTA DID Url path handling
Adjust implementation to changes in spec due to https://github.com/hyperledger/indy-did-method/pull/56

### PR DESCRIPTION
**Pull request by domwoe**
…y parameters

Resolves #13 

I've kept the RevRegDelta path for now as well.

Signed-off-by: Dominic Wörner <dom.woe@gmail.com>

### CODE REVIEW

**Comment by c2bo** [comment]
Finally got the time to test this, sorry for the delay :/
Looks good to me - my only question would be if we want to serve the ledger objects directly or also some form of metadata (e.g. stateproof) similar to how the did document is served.

**Comment by c2bo** [comment]
Finally got the time to test this, sorry for the delay :/
Looks good to me - my only question would be if we want to serve the ledger objects directly or also some form of metadata (e.g. stateproof) similar to how the did document is served.

**Comment by domwoe** [comment]
This should be the case.

Similar to `didDocumentMetadata` with a `node_response` field there's `contentMetadata` with a `node_response` field.

**Comment by c2bo** [comment]
I had to merge main into the branch and everything worked directly with `contentMetadata`, nice!

**Review by c2bo — APPROVED** [review]

**Pull request merged**
